# Generated by Django 2.1.5 on 2019-01-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='athour',
            field=models.CharField(default='admin', max_length=100, unique=True),
        ),
    ]
