# Generated by Django 2.1.5 on 2019-01-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20190130_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('100', 'Draft'), ('200', 'Published'), ('300', 'Rejected')], default='100'),
        ),
    ]
