# Generated by Django 2.1.5 on 2019-01-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20190130_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('10', 'Draft'), ('20', 'Published'), ('30', 'Rejected')], default='10'),
        ),
    ]
