# Generated by Django 2.1.5 on 2019-01-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190130_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(10, 'Draft'), (20, 'Published'), (30, 'Rejected')], default=10),
        ),
    ]
